# Generated by Django 4.2.16 on 2024-10-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttritionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('business_travel', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('daily_rate', models.IntegerField()),
                ('distance_from_home', models.IntegerField()),
                ('education', models.IntegerField()),
                ('job_role', models.CharField(max_length=50)),
                ('job_satisfaction', models.IntegerField()),
                ('monthly_income', models.IntegerField()),
                ('work_life_balance', models.IntegerField()),
                ('years_at_company', models.IntegerField()),
            ],
        ),
    ]
