# Generated by Django 4.2.16 on 2024-10-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attrition', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeAttritionModel',
        ),
    ]
